version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8082:8080"
      - "50000:50000"
    networks:
      - jenkins-network
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  testing-agent:
    image: jenkins/inbound-agent:latest
    container_name: testing-agent
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=TestingNode
      - JENKINS_SECRET=c4350d6a795822bfeb3be9917aaaef705eb805e4f1d3277290c81b8212174e58
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    networks:
      - jenkins-network
    volumes:
      - jenkins_agent:/home/jenkins/agent
    restart: always

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
  jenkins_agent:
