version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
      - mongo
    ports:
      - "3000:3000"

volumes:
  mongodb_data: